site_name: 阅读笔记
site_description: 日知其所亡，月无忘其所能，可谓好学也已矣。
site_author: tink
site_url: https://note.cyub.vip
strict: false

# Copyright
copyright: Copyright &copy; 2024 Tink

# Configuration
theme:
  name: material
  language: zh
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font: false
  favicon: images/favicon.png
  icon:
    logo: logo

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      type: iso_date
      enable_creation_date: true
  - glightbox
  - git-committers:
      repository: cyub/read-notes
      branch: main
  - markmap
  - rss:
      length: 1000
      use_git: true
      feeds_filenames:
        json_created: feed.json
        json_updated: feed-updated.json
        rss_created: feed.xml
        rss_updated: feed-updated.xml

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/solid/blog
      link: https://www.cyub.vip
      name: 个人博客
    - icon: fontawesome/brands/golang
      link: https://go.cyub.vip
      name: 《深入Go语言之旅》
    - icon: fontawesome/brands/github
      link: https://github.com/cyub
      name: 个人Github
    - icon: material/rss
      link: /feed.xml
      name: RSS Feed

extra_css:
  - "css/extra.css"
  - "https://cdn.jsdelivr.net/npm/roboto-font@0.1.0/css/fonts.min.css"
  - "https://cdn.jsdelivr.net/npm/typeface-roboto-mono@1.1.13/index.css"

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 首页: README.md
  - 小说:
      - 遥远的救世主: the-distant-savior/README.md
  - 编程:
      - "UNIX网络编程 卷1：套接字联网API": unp-v1/README.md
      - 操作系统导论: ostep/README.md
      - 多处理器编程的艺术: the-art-of-multiprocessor-programming/README.md
      - 深度探索Go语言: goruntime/README.md
      - "【斯坦福】cs106L:C++标准库编程": cs106L/README.md
